// Array of quotes
const quotes = [
    "The only way to do great work is to love what you do.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best revenge is massive success.",
"Don't watch the clock; do what it does. Keep going.",
"Life is what happens when you're busy making other plans.",
"The harder I work, the luckier I get.",
"The future depends on what you do today.",
"You miss 100% of the shots you don't take.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"Success is not in what you have, but who you are.",
"The greatest glory in living lies not in never falling, but in rising every time we fall.",
"I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
"The only person you are destined to become is the person you decide to be.",
"If you want to lift yourself up, lift up someone else.",
"In three words I can sum up everything I've learned about life: it goes on.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become.",
"Life is 10% what happens to us and 90% how we react to it.",
"It does not matter how slowly you go as long as you do not stop.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"The only place where success comes before work is in the dictionary.",
"You are never too old to set another goal or to dream a new dream.",
"The road to success and the road to failure are almost exactly the same.",
"Our greatest glory is not in never falling, but in rising every time we fall.",
"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
"The best revenge is massive success.",
"I find that the harder I work, the more luck I seem to have.",
"The only limit to our realization of tomorrow will be our doubts of today.",
"The future belongs to those who believe in the beauty of their dreams.",
"Don't watch the clock; do what it does. Keep going.",
"You miss 100% of the shots you don't take.",
"The harder I work, the luckier I get.",
"In the middle of every difficulty lies opportunity.",
"Success is not the key to happiness. Happiness is the key to success.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only way to do great work is to love what you do.",
"The biggest risk is not taking any risk.",
"Don't count the days; make the days count.",
"The best time to plant a tree was 20 years ago. The second-best time is now.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
"Success usually comes to those who are too busy to be looking for it.",
"Your time is limited, don't waste it living someone else's life.",
"The only person you should try to be better than is the person you were yesterday.",
"I have not failed. I've just found 10,000 ways that won't work.",
"The mind is everything. What you think you become."
];

// Function to generate a random quote
function generateRandomQuote() {
    const randomNumber = Math.floor(Math.random() * quotes.length);
    const quoteElement = document.getElementById("quote");
    quoteElement.textContent = quotes[randomNumber];
}

// Event listener for the button click
const generateButton = document.getElementById("generate-button");
generateButton.addEventListener("click", generateRandomQuote);

